ARCHS = armv7 arm64
include $(THEOS)/makefiles/common.mk

CFLAGS = -I..

BUNDLE_NAME = PowerSaverFlipswitch
PowerSaverFlipswitch_FILES = Switch.x
PowerSaverFlipswitch_FRAMEWORKS = UIKit
PowerSaverFlipswitch_LIBRARIES = flipswitch
PowerSaverFlipswitch_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk